services:
  - type: web
    name: kenyan-agro-price-api
    env: python
    region: oregon
    buildCommand: "pip install -r price_api/requirements.txt"
    startCommand: "cd price_api && gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
